### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by esaudet** [odarriba/docker-timemachine#30]
Hi, everything is in place but when I follow the proposed steps I get a permission denied on /timemachine into the docker container. I tried to create the user with a different uid & gid and set the permissions of my /external_drive on my host but it didn’t work. What I have found to work around this issue is creating the container with the —privileged=true setting. But, is there a way to adjust the permissions without this option ? Thanks !

**Comment by odarriba** [comment]
Hi there!

That will be probably because of the differences between the User ID and the Group ID of the folder you used in the data volume and the ones of the Docker container.

My suggestions are trying one of those: 

1. Do a chown inside the container to assign the volume to the current user.
2. Set the ownership of the folder to a user in your machine and assign that UID and GID to your container when you launch it.

Hope it helps, let us know!

**Comment by esaudet** [comment]
Excellent suggestion ! Sorry for the delay of my reply, I was doing a TimeMachine backup 👍
