### ISSUE TITLE
Interfering with existing SMB shares

### ISSUE THREAD

**Issue by jconly** [odarriba/docker-timemachine#63]
Hi, please forgive any ignorance.  Relatively new to Docker.
I recently did a fresh pull and run of the image, and it seems the container is now interfering with my already existing Samba server on the host machine.  Any advice?

Thank you.  Thinks have been working great so far!

**Comment by odarriba** [comment]
That´s the expected behaviour, since we are migrating to  SMB shares (you can see more info on #58), so it will be using the same port as your samba server and probably intefering with it.

Your best chance is to use an older image of the AFP protocol, or switch to another docker container that doesn't use SMB.

However, Apple is actively witching to SMB and that´s probabley the way to go. Maybe you can even configure the TimeMachine endpoint on your existing SMB server.
