### ISSUE TITLE
Permission denied when changing ownership of '/timemachine' and '/timemachine/System Volume Information'

### ISSUE THREAD

**Issue by AlexGustafsson** [odarriba/docker-timemachine#8]
Running the following command on a Windows host yields

```
docker run -h timemachine --name timemachine -e AFP_LOGIN=<YOUR_USER> -e AFP_PASSWORD=<YOUR_PASS> -e AFP_NAME=<TIME_MACHINE_NAME> -e AFP_SIZE_LIMIT=<MAX_SIZE_IN_MB> -d -v /route/to/your/timemachine:/timemachine -t -i -p 548:548 -p 636:636 odarriba/timemachine
```

the following logs for the container. The container won't start after being built.

```
chown: changing ownership of '/timemachine/System Volume Information': Permission denied
chown: changing ownership of '/timemachine': Permission denied
```

**Comment by odarriba** [comment]
Hi!

Container functionality to share volumes relies on the user and group ID's that docker assigns to folders. Due to some incompatibility, the image tries to set the correct permissions after start up.

I don't really know what happens to that permissions on a Windows host. Has your docker user permissions on the volume (that `System Volume Information` seems to be of the root of a Windows volume).

Another possible fix would be to use a folder inside the volume and not it's root. Can you try, please?

If that work, please let me know to update the README with specific instructions.

**Comment by odarriba** [comment]
@AlexGustafsson Any news on this?

**Comment by AlexGustafsson** [comment]
@odarriba You seem to be correct. I tried mounting `E:`(`-v /e/:/timemachine`) which threw the error. Making a directory directly under `E:`and then using it as the host side volume worked.

Thank you for your help.
